Mgate_formations_index_admin:
    path:  /admin/formations
    defaults: { _controller: MgateFormationBundle:Formation:index}
    methods:  [GET, HEAD]

Mgate_formations_lister:
    path:  /formations
    defaults: { _controller: MgateFormationBundle:Formation:lister}
    methods:  [GET, HEAD]

Mgate_formation_voir:
    path:  /formations/{id}
    defaults: { _controller: MgateFormationBundle:Formation:voir }
    requirements:
        id: \d+
    methods:  [GET, HEAD]

Mgate_formation_ajouter:
    path:  /admin/formations/ajouter
    defaults: { _controller: MgateFormationBundle:Formation:modifier, id : -1}
    methods:  [GET, HEAD, POST]

Mgate_formation_modifier:
    path:  /admin/formations/modifier/{id}
    defaults: { _controller: MgateFormationBundle:Formation:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

Mgate_formation_supprimer:
    path:  /admin/formations/supprimer/{id}
    defaults: { _controller: MgateFormationBundle:Formation:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

Mgate_formation_participation:
    path:  /admin/formations/participation
    defaults: { _controller: MgateFormationBundle:Formation:participation }
    methods:  [GET, HEAD]
