language: php
php:
  - 5.6
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - php bin/console doctrine:schema:validate
  - composer test
  - composer style:check
  - composer test:behat
