imports:
    - { resource: config.yml }

# Comment those lines to disable apcu caching of your entities
doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver: apcu
#        result_cache_driver: apcu # result cache is not used in Jeyser

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
            excluded_404s:
                - ^/
        grouped:
            type:    group
            members: [nested, buffered]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: "%technical_from%"
            to_email:   "%technical_to%"
            subject:    An Error Occurred!
            level:      error
