Mgate_indicateurs_index:
    path:  /admin/indicateurs
    defaults: { _controller: MgateStatBundle:Indicateurs:index }
    methods:  [GET, HEAD]

Mgate_indicateurs_ajax_suivi:
    path:  /admin/indicateurs/etudes
    defaults: { _controller: MgateStatBundle:Indicateurs:ajax }
    methods:  [GET, HEAD]

Mgate_indicateurs_debug:
    path:  /admin/indicateurs/{get}
    defaults: { _controller: MgateStatBundle:Indicateurs:debug}
    methods:  [GET, HEAD]
