Mgate_user_lister:
    path:  /user/lister
    defaults: { _controller: MgateUserBundle:Default:lister }
    methods:  [GET, HEAD]

Mgate_user_modifier:
    path:  /user/modifier/{id}
    defaults: { _controller: MgateUserBundle:Default:modifier }
    methods:  [GET, HEAD, POST]

Mgate_user_supprimer:
    path:  /user/supprimer/{id}
    defaults: { _controller: MgateUserBundle:Default:delete }
    methods:  [GET, HEAD, POST]


Mgate_user_addFromPersonne:
    path: /user/addFromPersonne/{id}
    defaults: { _controller: MgateUserBundle:Default:addUserFromPersonne }
    methods:  [GET, HEAD, POST]

