parameters:
#    Mgate_user.example.class: Mgate\UserBundle\Example

services:
    Mgate_user.password_resetting:
        class: Mgate\UserBundle\EventListener\RegistrationListener
        arguments: [ "@mailer", "@templating", "%technical_from%", "%technical_to%" ]
        tags:
            - { name: kernel.event_subscriber }
